import yagmail
import os
import datetime
import sys

# ================= CONFIGURATION =================
SENDER_EMAIL = "chocojazz1598@gmail.com"
APP_PASSWORD = "ryry ccno sgyc exaz"  # Gmail App Password (NOT your normal password)
RECEIVER_EMAIL = "chocoboy1598@gmail.com"
BODY = (
    "Dear Sir/Madam,\n\n"
    "Please find attached the latest attendance report generated by the "
    "Face Recognition Attendance System.\n\n"
    "Regards,\nFace Recognition Attendance System"
)
# =================================================

def send_latest_attendance():
    # Get today's date for subject
    date_str = datetime.date.today().strftime("%B %d, %Y")
    subject = f"Attendance Report - {date_str}"

    # Check if Attendance folder exists
    attendance_folder = "Attendance"
    if not os.path.exists(attendance_folder):
        print(f"[ERROR] Folder '{attendance_folder}' does not exist!")
        sys.exit(1)

    # Get list of CSV files
    files = [f for f in os.listdir(attendance_folder) if f.endswith(".csv")]
    if not files:
        print("[ERROR] No attendance files found in 'Attendance' folder.")
        sys.exit(1)

    # Find the latest file based on modification time
    latest_file = max([os.path.join(attendance_folder, f) for f in files], key=os.path.getmtime)

    # Initialize Yagmail
    try:
        yag = yagmail.SMTP(SENDER_EMAIL, APP_PASSWORD)
    except Exception as e:
        print(f"[ERROR] Failed to login: {e}")
        sys.exit(1)

    # Try sending the mail
    try:
        yag.send(
            to=RECEIVER_EMAIL,
            subject=subject,
            contents=BODY,
            attachments=latest_file
        )
        print(f"[INFO] Email Sent Successfully!\nAttached file: {latest_file}")
    except Exception as e:
        print(f"[ERROR] Failed to send email: {e}")
        sys.exit(1)

if __name__ == "__main__":
    send_latest_attendance()
